package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class test1Controller {
	@FXML
	private Button btn_1;
	@FXML
	private TextField text_1;
	@FXML
	private Button btn_11;
	@FXML
	private Button btn_12;

	// Event Listener on Button[#btn_1].onAction
	@FXML
	public void eventButton1(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_11].onAction
	@FXML
	public void eventButton2(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btn_12].onAction
	@FXML
	public void eventButton3(ActionEvent event) {
		// TODO Autogenerated
	}
}
